puts "The students on my cohort of Makers Academy"
puts "James Kemp"
puts "Nic Yeeles"
puts "Roi Driscoll"
puts "James Whyte"
puts "Margherita Serino"
puts "Vaidas Mykolaitis"
puts "Johann Bornman"
puts "Kate Hamilton"
puts "James Kemp"
puts "Nic Yeeles"
puts "Julie Walker"
puts "Will Allen"
puts "Julia Tan"
puts "Federico Maffei"
puts "Jamie Patel"
puts "Faezrah Rizalman"
puts "Josh Fail-Broon"
puts "Sasha Cooper"
puts "Nicolai DTH"
puts "Nadav Matalon"
puts "Fitsum Teklehaimanot"
print 21
puts " great students"